### PR TITLE
My 2nd pull request

### PR DESCRIPTION
**Pull request by elmar8287**
After correction from reviewer

### CODE REVIEW

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello @elmar8287 :wave:

__This is a brilliant effort from you. You've really done an amazing job so far. In this PR, here are my major highlights__

- You've submitted the expected PR link :+1: 
- Your commit messages are looking good :wink: 
- Proper use of GitHub flow :ok_hand: 

__However, you need to make some required changes before moving on to the next assignment. Please check my comments below and fix them as appropriate.__

### **Required Changes** :recycle: 
**[General Requirements](https://gitlab.com/microverse/guides/tse/code_review/code_review_guidelines_2_0/-/blob/master/general_requirements.md)**
- [ ] You've done an amazing job setting up the code linters. However, you need to ensure that all linter errors are fixed. Looking at your PR page, two(2) of your linter checks failed. 
shot
As a suggestion, you can run `npx hint .` (for webhint), and `npx stylelint "**/*.{css,scss}"` (for stylelint) on your local PC to see the linter errors and fix as appropriate. More information about this can be found [here](https://github.com/microverseinc/linters-config/tree/master/html-css-js). Please ensure that the linters are reporting no error before you request for another review.

- [x] Your Readme is really not descriptive. The project description, getting started and how-to-use sections should be present in your Readme. [This template](https://github.com/microverseinc/readme-template) might help.
- [x] You also need to ensure that your Pull Request has a descriptive title and summary, summarizing the changes are inside you've made. Your current PR title (My 2nd pull request) and summary (After correction from reviewer) do not really capture the feature/changes made in this PR. You can use something like `Hello Microverse Feature`, `First Project Feature`, or similar for your title. Your PR should have a short summary describing introduced changes in more detail.
- [x] Your .gitignore file would list the `node_modules` directory (as it can be added by accident while setting up linters). At the moment, you're only having `test.md` file in the `.gitignore`.


### **Optional Changes** :zap: 
N/A


* * *
**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. You can mention me (@teekaytech) so I can be notified about your comments and respond._

*REMINDER: As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).*

_**Please make the required changes and submit another review request when you are done.**_

* * *
Cheers,
_Reviewed by:_ [**Taofeek Olalere**](https://github.com/teekaytech)
__Happy coding :smiley:__

**Comment by elmar8287** [comment]
Add an html file main.html:

- insert H1 with text "Welcome to Microverse!"

Add css file styles.css:

- insert a single style for h1 with gree color

**Comment by elmar8287** [comment]
Dear @teekaytech,

I have made fixing as you marked from past. Please, review my code for submition.

Many thanks in advance,

My regards,

Elmar

**Comment by teekaytech** [comment]
> Dear @teekaytech,
> 
> I have made fixing as you marked from past. Please, review my code for submition.
> 
> Many thanks in advance,
> 
> My regards,
> 
> Elmar

Hi @elmar8287 

Thank you for reaching out. I believe the next available reviewer will claim and review your project. While you're waiting, please ensure that all linter checks are running and passing successfully.

Regards, 
Taofeek Olalere.

**Comment by elmar8287** [comment]
Dear @teekaytech,

I have checked all. Please, review my code.

My regards,

**Review by Shaher-11 — APPROVED** [review]
Hello @elmar8287 ,

# Congratulations! 🎉 
#### Your project is approved!  There is nothing else to say other than... it's time to merge it :muscle: :muscle: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Cheers and Happy coding!👏👏👏

**Comment by elmar8287** [comment]
Closing

**Pull request closed without merging**
